---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}
inputs:
  - name: resource-testV
  - name: resouce-logstash

run:
  path: /bin/sh
  args: 
    - -exc
    - |
      ls -ltr
      cd resource-testV
      ls -ltr
      cd ..
      mkdir test
      cp resource-testV/README.md test/
      cd test
      ls -ltr
      cat *.md
