---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}
inputs:
  - name: resource-testV

run:
  path: /bin/sh
  args: 
    - -exc
    - |
      ls -ltr
      cd resource-testV
      ls -ltr
      cd ..
      mkdir dmr
      cp resource-dmr/README.md dmr/
      cd dmr
      ls -ltr
      cat *.md
