resources:
  - name: resource-logstash
    type: git
    source:
      uri: https://github.com/rosh2707b/logstash.git
      branch: main

jobs:
  - name: job-clone
    public: true
    serial: true
    plan:
      - get: resource-logstash
        trigger: true
      - task: hello-world
        file: resource-logstash/task_hello_world.yml
